/**
 * Constants barrel file - re-exports all constants
 */

// API endpoints
export {
  API_BASE,
  AQL_ENDPOINT,
  COLLECTION_DOCUMENT_ENDPOINT,
  COLLECTION_ENDPOINT,
  COLLECTIONS_ENDPOINT,
  DOCUMENT_DETAILS_ENDPOINT,
  EDGE_FILTER_OPTIONS_ENDPOINT,
  GRAPH_ENDPOINT,
  NODES_DETAILS_ENDPOINT,
  SEARCH_ENDPOINT,
  SHORTEST_PATHS_ENDPOINT,
  SUNBURST_ENDPOINT,
} from "./api";

// External URLs
export {
  DEFAULT_FTU_ILLUSTRATION_URL,
  FTU_ILLUSTRATIONS_API_URL,
  FTU_ILLUSTRATIONS_JSONLD_URL,
} from "./external";

// Graph configuration defaults
export {
  DEFAULT_COLLAPSE_ON_START,
  DEFAULT_DEPTH,
  DEFAULT_EDGE_DIRECTION,
  DEFAULT_EDGE_FONT_SIZE,
  DEFAULT_FIND_SHORTEST_PATHS,
  DEFAULT_GRAPH_TYPE,
  DEFAULT_INCLUDE_INTER_NODE_EDGES,
  DEFAULT_LABEL_STATES,
  DEFAULT_NODE_FONT_SIZE,
  DEFAULT_NODE_LIMIT,
  DEFAULT_SET_OPERATION,
  DEFAULT_USE_FOCUS_NODES,
  EXPANSION_DEPTH,
  GRAPH_STATUS,
} from "./graph";
